apiVersion: v1
kind: Service
metadata:
  name: {{ include "order-execution-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "order-execution-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default 8080 }}
      protocol: TCP
      name: http
  selector:
    {{- include "order-execution-api.selectorLabels" . | nindent 4 }}
