replicaCount: 1

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

env:
  LOG_LEVEL: "debug"
  APP_ENV: "development"
  REFRESH_INTERVAL_MS: "2000"

affinity: {}
